version: '3.9'

services:

  app:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye

    volumes:
      - .:/workspace:cached

    command: sleep infinity

  mysql:
    image: mysql:8

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db

    ports:
      - "3306:3306"