spring.application.name=ecommerce

server.port=8080

# Define o Spring Profile ativo por padrão. Se for passado via argumento (--spring.profiles.active=prod), ele muda para prod.
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# H2 Console (Habilitado globalmente para facilitar desenvolvimento)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Outras configurações comuns
spring.thymeleaf.cache=false
spring.jpa.open-in-view=false
